name: 'Release to Github'
description: 'Release blocklet to Github Release'
inputs:
  token:
    description: 'token'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
