name: 'Release to Github'
description: 'Release blocklet to Github Release'
inputs:
  token:
    description: 'token'
    required: true
    default: ${{ github.token }}
  file-path:
    description: 'blocklet.json path'
    default: .blocklet/release/blocklet.json
    required: false
  working-directory:
    description: 'Working directory'
    default: ./
    required: false
  skip:
    description: 'Skip action'
    default: false
  skip-readme:
    description: 'Skip update readme'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
