name: Github release
env:
  MAIN_VERSION: 1

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Set yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: |
          yarn
          yarn global add @vercel/ncc

      - name: Build
        run: yarn build

      - name: Publish dist
        run: |
          git config --local user.name "bot"
          git config --local user.email "bot@arcblock.io"
          git add dist
          git commit --allow-empty -m "Github action build"
          git push origin main

      - name: Realese
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package-version.outputs.current-version}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Reset v${{ env.MAIN_VERSION }}
        run: |
          git tag -a v${{ env.MAIN_VERSION }} -m 'Sync with v${{ steps.package-version.outputs.current-version}}'
          git push origin v${{ env.MAIN_VERSION }} --force
