name: Github release

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install ncc
        run: yarn global add @vercel/ncc

      - name: Build
        run: yarn build

      - name: Get npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Publish dist
        run: |
          git config --local user.name "bot"
          git config --local user.email "bot@arcblock.io"
          git add dist
          git commit --allow-empty -m "Github action build"
          git tag -a v${{ steps.package-version.outputs.current-version}} -m "Release ${{ steps.package-version.outputs.current-version}}"
          git push --follow-tags
